export const productData = [
  {
    name: "Mountain Coffee Beans",
    shortDescription: "Premium arabica beans from high elevation",
    description: "Hand-picked arabica beans from 5000ft elevation, sun-dried and small-batch roasted.",
    price: 12.50,
    category: "Coffee & Tea",
    sku: "MCB-001",
    imageUrl: "https://images.pexels.com/photos/1695052/pexels-photo-1695052.jpeg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/1695052/pexels-photo-1695052.jpeg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234567",
    stockQuantity: 100,
    featured: true,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Sun-dried",
    harvestSeason: "Winter",
    shelfLife: "12 months",
    nutritionalInfo: "Rich in antioxidants",
    certifications: ["Organic", "Fair Trade"],
    origin: "High altitude mountains",
    varietyType: "Arabica"
  },
  {
    name: "Organic Black Pepper",
    shortDescription: "Bold, aromatic peppercorns from heritage vines",
    description: "Bold, aromatic peppercorns from heritage vines, traditionally sun-dried to preserve natural oils.",
    price: 8.95,
    category: "Spices",
    sku: "OBP-002",
    imageUrl: "https://images.pexels.com/photos/4198772/pexels-photo-4198772.jpeg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/4198772/pexels-photo-4198772.jpeg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234568",
    stockQuantity: 120,
    featured: true,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Sun-dried",
    harvestSeason: "Spring",
    shelfLife: "24 months",
    nutritionalInfo: "High in piperine",
    certifications: ["Organic"],
    origin: "Heritage farms",
    varietyType: "Black"
  },
  {
    name: "Premium Cardamom",
    shortDescription: "Large, intensely aromatic green cardamom pods",
    description: "Large, intensely aromatic green cardamom pods grown in virgin forest shade.",
    price: 9.25,
    category: "Spices",
    sku: "PC-003",
    imageUrl: "https://images.pexels.com/photos/4197444/pexels-photo-4197444.jpeg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/4197444/pexels-photo-4197444.jpeg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234567",
    stockQuantity: 85,
    featured: true,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Forest shade-dried",
    harvestSeason: "Monsoon",
    shelfLife: "18 months",
    nutritionalInfo: "Essential oils rich",
    certifications: ["Organic", "Wild harvested"],
    origin: "Virgin forest shade",
    varietyType: "Green"
  },
  {
    name: "Heirloom Rice",
    shortDescription: "Ancient grain variety from terraced paddies",
    description: "Ancient grain variety cultivated in terraced paddies using traditional methods for exceptional flavor.",
    price: 7.50,
    category: "Grains",
    sku: "HR-004",
    imageUrl: "https://pixabay.com/get/g8d45ceb30e78f76250dab3a606aa18bf8214f4a0ab35e8d44c5664dbb366d041807b1c61aa3772ea91f20ad4d34d417b94ee538479705a1b1d187d7c9e95f5f0_1280.jpg",
    imageUrls: ["https://pixabay.com/get/g8d45ceb30e78f76250dab3a606aa18bf8214f4a0ab35e8d44c5664dbb366d041807b1c61aa3772ea91f20ad4d34d417b94ee538479705a1b1d187d7c9e95f5f0_1280.jpg"],
    farmerId: "675e4d5a8b2c1a0001234568",
    stockQuantity: 150,
    featured: false,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Traditional milling",
    harvestSeason: "Winter",
    shelfLife: "12 months",
    nutritionalInfo: "High fiber, vitamins B",
    certifications: ["Heirloom variety"],
    origin: "Terraced paddies",
    varietyType: "Ancient grain"
  },
  {
    name: "Wild Forest Honey",
    shortDescription: "Raw, unprocessed honey from forest hives",
    description: "Pure, raw honey collected from wild forest beehives, unprocessed and unfiltered to preserve natural enzymes.",
    price: 11.00,
    category: "Sweeteners",
    sku: "WFH-005",
    imageUrl: "https://images.pexels.com/photos/33242/honey-sweet-syrup-organic.jpg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/33242/honey-sweet-syrup-organic.jpg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234569",
    stockQuantity: 75,
    featured: true,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Raw, unprocessed",
    harvestSeason: "Summer",
    shelfLife: "24 months",
    nutritionalInfo: "Natural enzymes, antioxidants",
    certifications: ["Wild harvested", "Raw"],
    origin: "Forest hives",
    varietyType: "Wildflower"
  },
  {
    name: "Turmeric Root",
    shortDescription: "Fresh, high-curcumin turmeric roots",
    description: "Fresh turmeric roots with high curcumin content, grown in mineral-rich soil without chemicals.",
    price: 6.75,
    category: "Spices",
    sku: "TR-006",
    imageUrl: "https://images.pexels.com/photos/6111568/pexels-photo-6111568.jpeg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/6111568/pexels-photo-6111568.jpeg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234570",
    stockQuantity: 200,
    featured: false,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Fresh harvested",
    harvestSeason: "Winter",
    shelfLife: "6 months fresh",
    nutritionalInfo: "High curcumin content",
    certifications: ["Organic", "Chemical-free"],
    origin: "Mineral-rich soil",
    varietyType: "High curcumin"
  },
  {
    name: "Moringa Leaves",
    shortDescription: "Nutrient-dense superfood leaves",
    description: "Fresh moringa leaves packed with vitamins, minerals, and antioxidants, harvested from pesticide-free trees.",
    price: 8.50,
    category: "Superfoods",
    sku: "ML-007",
    imageUrl: "https://images.pexels.com/photos/5692277/pexels-photo-5692277.jpeg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/5692277/pexels-photo-5692277.jpeg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234571",
    stockQuantity: 90,
    featured: false,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Air-dried",
    harvestSeason: "Year-round",
    shelfLife: "12 months",
    nutritionalInfo: "Vitamins A, C, E, protein",
    certifications: ["Superfood", "Pesticide-free"],
    origin: "Natural groves",
    varietyType: "Fresh leaves"
  },
  {
    name: "Himalayan Pink Salt",
    shortDescription: "Pure, unrefined pink salt crystals",
    description: "Unrefined pink salt crystals mined from ancient Himalayan deposits, rich in natural minerals.",
    price: 5.25,
    category: "Seasonings",
    sku: "HPS-008",
    imageUrl: "https://images.pexels.com/photos/1340116/pexels-photo-1340116.jpeg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/1340116/pexels-photo-1340116.jpeg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234572",
    stockQuantity: 300,
    featured: false,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Hand-mined",
    harvestSeason: "Year-round",
    shelfLife: "Indefinite",
    nutritionalInfo: "84 trace minerals",
    certifications: ["Unrefined", "Ancient"],
    origin: "Himalayan deposits",
    varietyType: "Pink crystals"
  },
  {
    name: "Coconut Oil",
    shortDescription: "Cold-pressed virgin coconut oil",
    description: "Cold-pressed virgin coconut oil from fresh coconuts, unrefined and rich in natural nutrients.",
    price: 9.95,
    category: "Oils",
    sku: "CO-009",
    imageUrl: "https://images.pexels.com/photos/3997993/pexels-photo-3997993.jpeg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/3997993/pexels-photo-3997993.jpeg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234573",
    stockQuantity: 110,
    featured: true,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Cold-pressed",
    harvestSeason: "Year-round",
    shelfLife: "24 months",
    nutritionalInfo: "MCT oils, vitamin E",
    certifications: ["Virgin", "Cold-pressed"],
    origin: "Coastal groves",
    varietyType: "Virgin"
  },
  {
    name: "Sesame Oil",
    shortDescription: "Traditional wood-pressed sesame oil",
    description: "Traditional wood-pressed sesame oil from heritage seeds, maintaining authentic flavor and nutrients.",
    price: 7.80,
    category: "Oils",
    sku: "SO-010",
    imageUrl: "https://images.pexels.com/photos/4198890/pexels-photo-4198890.jpeg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/4198890/pexels-photo-4198890.jpeg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234574",
    stockQuantity: 95,
    featured: false,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Wood-pressed",
    harvestSeason: "Winter",
    shelfLife: "18 months",
    nutritionalInfo: "Healthy fats, vitamin E",
    certifications: ["Traditional method", "Heritage seeds"],
    origin: "Family farms",
    varietyType: "Heritage"
  },
  {
    name: "Green Tea Leaves",
    shortDescription: "Hand-picked high-altitude green tea",
    description: "Hand-picked green tea leaves from high-altitude gardens, naturally processed to preserve antioxidants.",
    price: 13.25,
    category: "Coffee & Tea",
    sku: "GTL-011",
    imageUrl: "https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234575",
    stockQuantity: 80,
    featured: true,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Natural processing",
    harvestSeason: "Spring",
    shelfLife: "24 months",
    nutritionalInfo: "High in antioxidants, EGCG",
    certifications: ["High altitude", "Hand-picked"],
    origin: "Mountain gardens",
    varietyType: "Green"
  },
  {
    name: "Millet Flour",
    shortDescription: "Stone-ground ancient grain flour",
    description: "Stone-ground millet flour from drought-resistant ancient grains, perfect for gluten-free baking.",
    price: 6.50,
    category: "Grains",
    sku: "MF-012",
    imageUrl: "https://images.pexels.com/photos/5560019/pexels-photo-5560019.jpeg?auto=compress&cs=tinysrgb&w=800",
    imageUrls: ["https://images.pexels.com/photos/5560019/pexels-photo-5560019.jpeg?auto=compress&cs=tinysrgb&w=800"],
    farmerId: "675e4d5a8b2c1a0001234576",
    stockQuantity: 125,
    featured: false,
    naturallyGrown: true,
    chemicalFree: true,
    processingMethod: "Stone-ground",
    harvestSeason: "Summer",
    shelfLife: "6 months",
    nutritionalInfo: "Gluten-free, high protein",
    certifications: ["Ancient grain", "Gluten-free"],
    origin: "Dryland farms",
    varietyType: "Ancient"
  }
];